name: Test to Main
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  schedule:
    - cron: '40 17 */7 * *'
  
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d %b %Y')"
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: test
          # Ensure all branches are available locally
          fetch-tags: true
      - name: Check for commits between test and main
        id: check_commits
        run: |
          if [ -z "$(git log main..test)" ]; then
            echo "No commits between test and main. Skipping PR creation."
            exit 0
          fi
      
      - name: create pull request
        if: steps.check_commits.outcome == 'success'
        run: gh pr create -B main -H test --title 'Release ${{ steps.date.outputs.date }} Test to Main' --body 'Created by Github action' \
          || gh pr edit -B main --title 'Release ${{ steps.date.outputs.date }} Test to Main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
